<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MallDsm" nsURI="http://mall.com" nsPrefix="Mall">
  <eClassifiers xsi:type="ecore:EClass" name="Shop" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" upperBound="-1" eType="#//Container"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soldGoods" upperBound="-1"
        eType="#//ListedGood" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" upperBound="-1"
        eType="#//Employee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manager" lowerBound="1"
        eType="#//Employee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="openSchedule" lowerBound="1"
        eType="#//WeeklySchedule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PhotosPaths">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MapPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BrandShop" eSuperTypes="#//Shop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brand" lowerBound="1" eType="#//Brand"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecialisticShop" eSuperTypes="#//Shop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="speciality" lowerBound="1"
        eType="#//Category"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Brand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="producedGoods" upperBound="-1"
        eType="#//Good" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedGood" upperBound="-1"
        eType="#//ItemInStock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Good">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasSubCategory" lowerBound="1"
        eType="#//SubCatecory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ModelNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemInStock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" lowerBound="1"
        eType="#//Good"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemCount" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListedGood">
    <eStructuralFeatures xsi:type="ecore:EReference" name="good" lowerBound="1" eType="#//Good"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sales" upperBound="-1"
        eType="#//Discount" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPrice" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubCatecory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//SubCatecory" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="shiftSchedule" lowerBound="1"
        eType="#//WeeklySchedule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeSpan">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StartHour" upperBound="23"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StartDay" lowerBound="1"
        upperBound="7" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EndDay" lowerBound="1"
        upperBound="7" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EndHour" upperBound="23"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeeklySchedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Shift" upperBound="-1"
        eType="#//TimeSpan" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Discount">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" upperBound="100"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shelf" eSuperTypes="#//Container">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layers" lowerBound="2"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Refrigerator" eSuperTypes="#//Container"/>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//Container"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="shops" upperBound="-1"
        eType="#//Shop" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aviableBrands" upperBound="-1"
        eType="#//Brand" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
